### ISSUE TITLE
Buttons 4 - 10 doesn't have effect at latest Chrome

### ISSUE THREAD

**Issue by NeXTs** [codrops/DistortedButtonEffects#3]
Chrome 53.0.2785.143 m
Win8

Button 4 has effect but not great as before (I've checked it like two months ago and everything worked great), in FF all buttons still playing as expected.

Do you know what may be changed in Chrome that breaks effect animation?

**Comment by Grsmto** [comment]
Actually Chrome changed the way the handle the filters urls. So basically on the live article it doesn't work at all for me.
I'll take a look and try to fix it.

**Comment by NeXTs** [comment]
I must admit that buttons in this repo works just fine.
Buttons are broken at codrop's article.
The problem is - most of the people don't clone & install repo to see effect, they look at it at codrops article.

@codrops So that if you change all
`filter: url(../#filter-goo-4);`
to
`filter: url(#filter-goo-4);`
[at this demo page](http://tympanus.net/Development/DistortedButtonEffects/) it should be fine at chrome again

**Comment by NeXTs** [comment]
Ha! My apologies, just noticed @Grsmto made a commit yesterday with some changed, that's why it works now..

Don't mind me )

**Comment by NeXTs** [comment]
@Grsmto Thank you for such a quick response!
